### ISSUE TITLE
decode reports wrong attributes when a new Dictionary with VENDOR is added

### ISSUE THREAD

**Issue by borushka** [retailnext/node-radius#35]
To reproduce :
1. into auth_server.js add radius.add_dictionary with https://github.com/ates/radius/blob/master/priv/dictionary.3gpp
2. run auth_server.js and auth_client.js
3. the decoded packet has wrong attribute names
3GPP-Charging-Gateway-Address = "10.5.5.5"
3GPP-Charging-ID = 880921834
3GPP-IMSI = "jlpicard"

**Comment by muirrn** [comment]
Thank you for your report.

This library does not currently support dictionaries using the implicit attribute prefix method of specifying the vendor. If you add an explicit "BEGIN-VENDOR 3GPP" ... "END-VENDOR 3GPP" block around the attributes, it should work. See http://freeradius.org/radiusd/man/dictionary.html for more information.

**Comment by borushka** [comment]
Thanks for the prompt reply. You can easily fix it in radius.js. Just add the line code marked in bold.

    var match = line.match(/^\s*VENDOR\s+(\S+)\s+(\d+)/);
    if (match) {
      vendor_name_to_id[match[1]] = match[2];
      **vendor = match[1];**
      continue;
    }

**Comment by muirrn** [comment]
It seems like that would work, but according to the freeradius man page, the "VENDOR" directive only defines a vendor (it does not imply the below attributes VSAs are for that vendor, as your patch infers). For example, you could have a dictionary that declares multiple vendors at the top, then declares attributes for each vendor below.

Based on the documentation, the correct approach is to look at the prefix of the attribute name (e.g. "3GPP-IMSI") and see that the previously defined vendor "3GPP" is a prefix if the attribute name. This is a pretty lame way to do it, which is why we prefer the explicit BEGIN-VENDOR/END-VENDOR.

**Comment by borushka** [comment]
Thanks for the detailed explanation.
