### ISSUE TITLE
Openwrt, Linux

### ISSUE THREAD

**Issue by boredland** [retailnext/node-radius#43]
Hi there! I try to use this from linux and via openwrt. I configured a WPA-EAP network and a server that listens to the radius requests using this library. Sadly, the user-password doesn't get decrypted. I guess this is due to me having either not configured openwrt or my computer correctly. What seem to be the correct configurations for the router and the end-points?

As of now i have for
---

Client:

Security: WPA & WPA2 Enterprise
Auth: Tunneled TLS
Inner Auth: PAP
user: user
password: pass

---

Openwrt Router:
Encryption: WPA-EAP
Cipher: CCMP and TKIP

**Comment by psanford** [comment]
I've not tried using TTLS+PAP before, but based on rfc5281 it sounds like it should work with node-radius.

The most obvious thing to check is to make sure the shared secret between the router and the node-radius instance is the same.

**Comment by boredland** [comment]
Here the config details from openwrts luci and my client pc.
![luci_eap](https://user-images.githubusercontent.com/4662748/40128652-6da510bc-5932-11e8-8541-9badec05e2a4.png)
![wifi_ui_eap](https://user-images.githubusercontent.com/4662748/40128662-73bd0b30-5932-11e8-86aa-0117f075c7b0.png)

The shared secret is "abc".
[pcap.zip](https://github.com/retailnext/node-radius/files/2009910/pcap.zip)

**Comment by psanford** [comment]
The Access-Request packet in that pcap doesn't have a User-Password attribute in it. The packet does include an inner EAP-Message, but node-radius doesn't support that (see #29). 

I'm not sure if the issue is that your router isn't actually configured to do TTLS/PAP or that TTLS/PAP doesn't set the User-Password attribute. 

In any case the Access-Request payload will need to have the User-Password attribute set in order to do user auth via node-radius.
