### ISSUE TITLE
RADIUS server issue ChangeOfAuthorization (CoA) requests

### ISSUE THREAD

**Issue by reigelgallarde** [retailnext/node-radius#46]
Thank you for making this radius in node. I'm using it in my project.
I've checked the example but can't find something related to CoA.

Is it possible?
I'm using CoovaChilli, and the radius is working great on Authentication and Accounting.
But searching for days now on how to make it that the radius can send a termination on sessions.

Currently, I'm using child_process.exec() to spawn a chilli_query command to disconnect a user.
Would be a game changer if the radius itself can do it.

Any help is appreciated.

**Comment by psanford** [comment]
I'm not familiar with the CoA workflow. I assume you are talking about RFC5176?

Based on a cursory skim of that RFC it looks like it uses pretty normal radius payloads. node-radius already has definitions in its code map for CoA-Request, CoA-ACK and CoA-NAK. If it doesn't work today the changes required to support it would probably be fairly minimal.

Unfortunately, since I'm not familiar with CoA I'm afraid I'm not going to be of much help providing a working example. I would suggest reading through the relevant sections of RFC5176 and then examining a packet capture of an existing working system sending CoA messages.

**Comment by reigelgallarde** [comment]
It took me a while, but I've found the answer to my question.
For the benefit of those who are looking for the same, I'm putting this simple code.

````
var radius = require('radius');
var dgram = require("dgram");
var server = dgram.createSocket("udp4");
var encoded = radius.encode({
    code: 'Disconnect-Request',
    secret: 'testing123',
    attributes: [
        ['User-Name', 'test-user'],
    ]
});

server.on('listening', () => {
    server.send(encoded, 0, encoded.length, '3799', '127.0.0.1', (err, bytes) => {
        if (err) {
            console.log('Error sending response to ');
            console.log(err);
        }
        console.log(bytes);
        server.close();
    });
});

server.bind({
  address: '127.0.0.1',
  port: 1812
});
````

`encoded` above is the minimal packet that needs to be sent to CoovaChilli.
With this the device with a username `test-user` will get disconnected.

**Comment by lirantal** [comment]
thanks for sharing @reigelgallarde

**Comment by reigelgallarde** [comment]
hello @lirantal, Are you in some way doing the same or have a project like this?
If you have a github of it, I would love to check it out. Or I might be of help in some parts.

Regards!

**Comment by lirantal** [comment]
Not really. I'm silently following along but not maintaining daloradius anymore.
